# Generated by Django 5.1.1 on 2026-09-02 03:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('smmlv', models.DecimalField(decimal_places=2, help_text='Salario mínimo mensual legal vigente', max_digits=12, verbose_name='SMMLV')),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tope_auxilio_transporte_smmlv', models.PositiveSmallIntegerField(default=2, help_text='Aplica si salario <= N SMMLV')),
                ('porcentaje_salud_empleado', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5)),
                ('porcentaje_salud_empleador', models.DecimalField(decimal_places=2, default=Decimal('8.50'), max_digits=5)),
                ('porcentaje_pension_empleado', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5)),
                ('porcentaje_pension_empleador', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('porcentaje_arl_base', models.DecimalField(decimal_places=4, default=Decimal('0.5220'), max_digits=5)),
                ('porcentaje_sena', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('porcentaje_icbf', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('porcentaje_caja_compensacion', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5)),
            ],
            options={
                'verbose_name': 'parámetro de nómina',
                'verbose_name_plural': 'parámetros de nómina',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('LIQUIDADO', 'Liquidado'), ('APROBADO', 'Aprobado'), ('PAGADO', 'Pagado')], default='BORRADOR', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parametros', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.parametronomina')),
            ],
            options={
                'verbose_name': 'período de nómina',
                'verbose_name_plural': 'períodos de nómina',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HE_DIURNA', 'Hora Extra Diurna (25%)'), ('HE_NOCTURNA', 'Hora Extra Nocturna (75%)'), ('HE_DOM_DIURNA', 'Hora Extra Dominical Diurna (100%)'), ('HE_DOM_NOCTURNA', 'Hora Extra Dominical Nocturna (150%)'), ('INCAPACIDAD', 'Incapacidad'), ('VACACIONES', 'Vacaciones'), ('LICENCIA', 'Licencia'), ('BONIFICACION', 'Bonificación'), ('COMISION', 'Comisión'), ('DEDUCCION', 'Deducción'), ('PRESTAMO', 'Descuento por Préstamo'), ('LIBRANZA', 'Descuento por Libranza')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Horas, días o unidades según el tipo', max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor fijo (para bonificaciones, deducciones, etc.)', max_digits=12)),
                ('observacion', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='core.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='payroll.periodonomina')),
            ],
            options={
                'verbose_name': 'novedad',
                'verbose_name_plural': 'novedades',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=30)),
                ('salario_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_horas_extra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_bonificaciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_comisiones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('aporte_salud_empleado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('aporte_pension_empleado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_otras_deducciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('aporte_salud_empleador', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('aporte_pension_empleador', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('aporte_arl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('aporte_sena', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('aporte_icbf', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('aporte_caja_compensacion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('liquidado_en', models.DateTimeField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='core.contrato')),
                ('liquidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='payroll.periodonomina')),
            ],
            options={
                'verbose_name': 'nómina',
                'verbose_name_plural': 'nóminas',
                'ordering': ['contrato__empleado__primer_apellido'],
                'unique_together': {('periodo', 'contrato')},
            },
        ),
    ]
