# Generated by Django 5.1.1 on 2026-09-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametronomina',
            name='smmlv',
            field=models.DecimalField(decimal_places=2, help_text='Salario minimo mensual legal vigente', max_digits=12, verbose_name='SMMLV'),
        ),
    ]
